update_fastlane

default_platform(:ios)

platform :ios do
    desc "Run all tests"
    lane :test do
        scan(
        scheme: "UICircularProgressRing-Package",
        code_coverage: true
        )
    end
end
